# Generated by Django 5.1.4 on 2024-12-05 11:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Party_name', models.CharField(max_length=50)),
                ('party_phone_number', models.CharField(default=0, max_length=10)),
                ('party_address', models.CharField(max_length=100)),
                ('referance', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=50)),
                ('staff_id', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nature_of_work', models.CharField(max_length=255)),
                ('Details', models.CharField(max_length=255)),
                ('Status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('cancelled', 'cancelled')], default='Pending', max_length=255)),
                ('Finished_date', models.DateField()),
                ('Delivery_Date', models.DateField()),
                ('Bill_Amount', models.CharField(max_length=255)),
                ('Fee_amount', models.CharField(max_length=255)),
                ('DOR', models.DateField(default=datetime.date.today)),
                ('Assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dec_app.staff')),
                ('Party_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dec_app.party')),
            ],
        ),
    ]
