# Generated by Django 5.1.4 on 2024-12-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dec_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_details',
            name='Bill_Amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='work_details',
            name='Delivery_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work_details',
            name='Fee_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='work_details',
            name='Finished_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
